server:
  port: 8001

spring:
  application:
    name: library-app

  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

